export default [
    {
        "id" : 1,
        "img" : "1.jpeg",
        "name" : "Prashanta K Baishya",
        "location" : "Guwahati",
        "comment" : "Highly impressed with Devarshi's astrological analysis. He is not only a bold predictor but his prediction reflects his depth study and good skill in the subjects.",
    },
    {
        "id" : 2,
        "img" : "2.jpeg",
        "name" : "Devkant Swargiary",
        "location" : "Auckland, New Zealand",
        "comment" : "The remedial suggestions imparted by Devarshi were extremely helpful. The weaknesses could be worked upon and the strengths could be reinstated/ reinforced upon knowing them.",
    },
    {
        "id" : 3,
        "img" : "3.jpeg",
        "name" : "Abhijit",
        "location" : "Saharanpur, Uttar Pradesh",
        "comment" : "First came to know about his astrology relation from his Facebook post asked a few questions and later on a few major concerns related to my career and life. Absolutely bang on predictions and what makes him diffrent is NO BIG TANTRA MANTRA , simple remedies which are easy to do. Waiting for my long term target to be achieved with his help. Om Namah Shivay.",
    },
    {
        "id" : 4,
        "img" : "4.jpeg",
        "name" : "Namrata",
        "location" : "Mumbai",
        "comment" : "Sir, u are a blessing from God to help people with your knowledge and wisdom. You have always been there with inspirational advice through all of my ups and downs. I rely on your guidance to help me get through my hardest times. Your reading makes me feel hopeful, happy, and grateful for my attributes. I'd like to thank you for providing me hope when I couldn't see any.",
    },
    {
        "id" : 5,
        "img" : "5.jpeg",
        "name" : "Sameer",
        "location" : "Maithan, Jharkhand",
        "comment" : "'Jyotish'. This word used to fill my mind with all kind of negative opinion. I used to think this whole knowledge as a hoax. As I was introduced to this knowledge by him I was thrilled and amused how accurate and brilliant this vidya called 'JYOTISH' is and also a bit disappointed how I used to see it. His predictions are very accurate and the best part is that gives the best remedies to those problems that he sees in your birth chart.",
    },
    {
        "id" : 6,
        "img" : "6.jpeg",
        "name" : "Tanmay",
        "location" : "Panjim, Goa",
        "comment" : "I always wanted to know how the astrologers can tell someone's future, is there any science behind it really? But when I met Devarshi Daa, he showed me the whole analysis clearly. No one will tell about their studies, they only tell future but how they got to know that, we are never told. But Devarshi daa tells what you need and why this is happening  and how he knew that this is happening to you.",
    },
    {
        "id" : 7,
        "img" : "7.jpeg",
        "name" : "Bornali",
        "location" : "Hungary",
        "comment" : "Devarshi da, I would like to take this opportunity to express my heartfelt gratitude to you for bringing optimism into my life. Your sincere, truthful and faultless intuition through the spirit of astrology has profoundly contributed in providing stability to my personal and professional life for which I'm extremely thankful. Your analysis is indisputable and astute and the transparency with which you bring meaning into the planetary transits and influences is deeply acknowledged.",
    },
    {
        "id" : 8,
        "img" : "8.jpeg",
        "name" : "Priyasmi",
        "location" : "Delhi",
        "comment" : "Trustworthy would just be the word that I would use to define Devarshi Dutta and his astrology based readings and analysis. In a world full of quacks, amateurs and fake astrologers who have destroyed the credibility of such an ancient science and who have been running scams and setting up their shops just for money while they have very little knowledge about this practice",
    },
    {
        "id" : 9,
        "img" : "9.jpeg",
        "name" : "Damayanti",
        "location" : "Kolkata",
        "comment" : "I met Devarshi on Facebook quite a few years back. But I actually came to know him through his deep knowledge of astrology. I was heavily influenced by one of the books that he had written on astrology and which I had read. His predictions and solutions were so good and comforting that I recommended all my family members and a few friends as well to get in touch with him. His remedies are simple and he does not ask to purchase expensive gems and rings.",
    },
    {
        "id" : 10,
        "img" : "10.jpeg",
        "name" : "Bhagyashree",
        "location" : "Guwahati",
        "comment" : "Excellent consultation experience. Initially I was sceptical due to my previous bad experiences with other astrologers but his empathy towards his clients stands out among other qualities. I didn't spend a penny on costly gemstones, yet got a full solution to my issues at home. Most recommended!",
    },
]